
name: Master Branch

on:
 push:
   branches:
     - master
   paths:
     - 'src/**'
     - '.github/**'
     - 'pom.xml'

jobs:
  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-18.04

    steps:
      - name: Publish artifact on GitHub Packages
        uses: qcastel/github-actions-maven-release@master
        with:
         release-branch-name: "master"
         git-release-bot-name: "release-bot"
         git-release-bot-email: "asrivastav@gainsight.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
